[context.production]
  command = "APP_ENVIRONMENT=production BASE_URL=$PROD_BASE_URL API_VERSION=$PROD_API_VERSION NUXT_ENV_URL_LANDING_PAGE=$PROD_URL_LANDING_PAGE  npm run generate"

[context.main]
  command = "APP_ENVIRONMENT=development BASE_URL=$STAGING_BASE_URL API_VERSION=$STAGING_API_VERSION NUXT_ENV_URL_LANDING_PAGE=$STAGING_URL_LANDING_PAGE npm run generate"

[context.deploy-preview]
  command = "APP_ENVIRONMENT=development BASE_URL=$STAGING_BASE_URL API_VERSION=$STAGING_API_VERSION NUXT_ENV_URL_LANDING_PAGE=$STAGING_URL_LANDING_PAGE npm run generate"

[[redirects]]
  from = "/*"
  to = "/index.html/"
  status = 200
  